
export const userTypes = {
    LOGIN: 'LOGIN',
    SIGNUP: 'SIGNUP',
    SAVE_SPOTIFY :'SAVE_SPOTIFY',
    UPDATE_USER: 'UPDATE_USER',
    UPDATE_PROFILE_PICTURE: 'UPDATE_PROFILE_PICTURE',
    USER_LOGOUT : 'USER_LOGOUT',
    RESTORE_TOKEN : "RESTORE_TOKEN"
 }